package com.github.bumblebee202111.minusonecloudmusic.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
@Suppress("PropertyName")
data class DolphinColors(
    val avatarBg1: Color = Color.Unspecified,
    val avatarBg2: Color = Color.Unspecified,
    val avatarBg3: Color = Color.Unspecified,
    val avatarBg4: Color = Color.Unspecified,
    val avatarBg5: Color = Color.Unspecified,
    val avatarBg6: Color = Color.Unspecified,
    val backgroundAndroid: Color = Color.Unspecified,
    val backgroundDual: Color = Color.Unspecified,
    val backgroundIOS: Color = Color.Unspecified,
    val backgroundWhite: Color = Color.Unspecified,
    val brand1: Color = Color.Unspecified,
    val brand2: Color = Color.Unspecified,
    val brand3: Color = Color.Unspecified,
    val brand4: Color = Color.Unspecified,
    val brand5: Color = Color.Unspecified,
    val brand6: Color = Color.Unspecified,
    val brand7: Color = Color.Unspecified,
    val brand8: Color = Color.Unspecified,
    val brand9: Color = Color.Unspecified,
    val brand10: Color = Color.Unspecified,
    val icon1: Color = Color.Unspecified,
    val icon2: Color = Color.Unspecified,
    val icon3: Color = Color.Unspecified,
    val icon4: Color = Color.Unspecified,
    val icon5: Color = Color.Unspecified,
    val icon6: Color = Color.Unspecified,
    val icon7: Color = Color.Unspecified,
    val iconDual1: Color = Color.Unspecified,
    val iconDual1_1: Color = Color.Unspecified,
    val iconDual2: Color = Color.Unspecified,
    val iconDual2_1: Color = Color.Unspecified,
    val iconDual3: Color = Color.Unspecified,
    val iconDual4: Color = Color.Unspecified,
    val iconDual5: Color = Color.Unspecified,
    val iconDual6: Color = Color.Unspecified,
    val iconDual7: Color = Color.Unspecified,
    val iconDual7_1: Color = Color.Unspecified,
    val iconDual7_2: Color = Color.Unspecified,
    val iconDual8: Color = Color.Unspecified,
    val iconDual9: Color = Color.Unspecified,
    val iconOnimage1: Color = Color.Unspecified,
    val iconOnimage2: Color = Color.Unspecified,
    val iconOnimage3: Color = Color.Unspecified,
    val iconOnimage4: Color = Color.Unspecified,
    val iconOnimage5: Color = Color.Unspecified,
    val iconOnimage6: Color = Color.Unspecified,
    val iconOnimage7: Color = Color.Unspecified,
    val neutral3: Color = Color.Unspecified,
    val neutral4: Color = Color.Unspecified,
    val neutral5: Color = Color.Unspecified,
    val neutral6: Color = Color.Unspecified,
    val neutral6_1: Color = Color.Unspecified,
    val neutral7: Color = Color.Unspecified,
    val neutral7_1: Color = Color.Unspecified,
    val neutral8: Color = Color.Unspecified,
    val neutral8_1: Color = Color.Unspecified,
    val neutral9: Color = Color.Unspecified,
    val neutral10: Color = Color.Unspecified,
    val neutral11: Color = Color.Unspecified,
    val primary1: Color = Color.Unspecified,
    val primary2: Color = Color.Unspecified,
    val primary3: Color = Color.Unspecified,
    val primary4: Color = Color.Unspecified,
    val primary5: Color = Color.Unspecified,
    val primary6: Color = Color.Unspecified,
    val primary7: Color = Color.Unspecified,
    val secondary1_1: Color = Color.Unspecified,
    val secondary1_2: Color = Color.Unspecified,
    val secondary1_3: Color = Color.Unspecified,
    val secondary2_1: Color = Color.Unspecified,
    val secondary2_2: Color = Color.Unspecified,
    val secondary2_3: Color = Color.Unspecified,
    val secondary2_4: Color = Color.Unspecified,
    val secondary3: Color = Color.Unspecified,
    val secondary4: Color = Color.Unspecified,
    val secondary5: Color = Color.Unspecified,
    val secondary6: Color = Color.Unspecified,
    val secondary7: Color = Color.Unspecified,
    val secondary7_2: Color = Color.Unspecified,
    val secondary8: Color = Color.Unspecified,
    val secondary9: Color = Color.Unspecified,
    val skinElement1: Color = Color.Unspecified,
    val skinElement2: Color = Color.Unspecified,
    val skinElement3: Color = Color.Unspecified,
    val skinElement4: Color = Color.Unspecified,
    val skinElement5: Color = Color.Unspecified,
    val skinElement6: Color = Color.Unspecified,
    val skinElement7: Color = Color.Unspecified,
    val skinElement10: Color = Color.Unspecified,
    val text1: Color = Color.Unspecified,
    val text2: Color = Color.Unspecified,
    val text2_1: Color = Color.Unspecified,
    val text3: Color = Color.Unspecified,
    val text3_1: Color = Color.Unspecified,
    val text4: Color = Color.Unspecified,
    val text4_1: Color = Color.Unspecified,
    val text5: Color = Color.Unspecified,
    val text5_1: Color = Color.Unspecified,
    val text6: Color = Color.Unspecified,
    val text6_1: Color = Color.Unspecified,
    val text7: Color = Color.Unspecified,
    val textDual1: Color = Color.Unspecified,
    val textDual2: Color = Color.Unspecified,
    val textDual3: Color = Color.Unspecified,
    val textDual4: Color = Color.Unspecified,
    val textDual5: Color = Color.Unspecified,
    val textDual6: Color = Color.Unspecified,
    val textOnimage1: Color = Color.Unspecified,
    val textOnimage1_1: Color = Color.Unspecified,
    val textOnimage2: Color = Color.Unspecified,
    val textOnimage3: Color = Color.Unspecified,
    val textOnimage3_1: Color = Color.Unspecified,
    val textOnimage4: Color = Color.Unspecified,
    val textOnimage5: Color = Color.Unspecified,
    val textOnimage6: Color = Color.Unspecified,
    val textOnimage7: Color = Color.Unspecified,
    val textOnimage8: Color = Color.Unspecified,
    val textOnimage9: Color = Color.Unspecified,
    val textOnimage10: Color = Color.Unspecified,
)

@Immutable
data class DolphinShadows(
    val bubble: DolphinShadow = DolphinShadow(),
    val dark: DolphinShadow = DolphinShadow(),
    val gray: DolphinShadow = DolphinShadow(),
    val normal: DolphinShadow = DolphinShadow(),
    val redBtn: DolphinShadow = DolphinShadow(),
    val redIcon: DolphinShadow = DolphinShadow(),
    val toast: DolphinShadow = DolphinShadow(),
)

private val lightMaterialColorScheme = lightColorScheme(
    primary = dolphinColorPrimary1White,
    onPrimary = dolphinColorTextOnimage1White,
    primaryContainer = dolphinColorPrimary7White,
    onPrimaryContainer = dolphinColorPrimary1White,
    secondary = dolphinColorSecondary2_1White,
    onSecondary = dolphinColorTextOnimage1White,
    secondaryContainer = dolphinColorSecondary2_4White,
    onSecondaryContainer = dolphinColorSecondary2_1White,
    tertiary = dolphinColorSecondary7White,
    onTertiary = dolphinColorTextOnimage1White,
    tertiaryContainer = dolphinColorSecondary7_2White,
    onTertiaryContainer = dolphinColorSecondary7White,
    error = dolphinColorSecondary4White,
    onError = dolphinColorTextOnimage1White,
    errorContainer = dolphinColorPrimary7White,
    onErrorContainer = dolphinColorPrimary1White,
    background = dolphinColorBackgroundAndroidWhite,
    onBackground = dolphinColorText1White,
    surface = dolphinColorBackgroundDualWhite,
    onSurface = dolphinColorText1White,
    onSurfaceVariant = dolphinColorText3_1White,
    outlineVariant = dolphinColorText7White,
    scrim = dolphinColorText4_1White,
    outline = dolphinColorText6_1White,
    surfaceVariant = dolphinColorSkinElement1White,
    inverseSurface = dolphinColorBackgroundDualBlack,
    inverseOnSurface = dolphinColorText1Black,
    inversePrimary = dolphinColorPrimary1Black,
    surfaceDim = dolphinColorSkinElement1White,
    surfaceBright = dolphinColorBackgroundWhiteWhite,
    surfaceContainerLowest = dolphinColorBackgroundAndroidWhite,
    surfaceContainerLow = dolphinColorSkinElement1White,
    surfaceContainer = dolphinColorBackgroundWhiteWhite,
    surfaceContainerHigh = dolphinColorNeutral5White,
    surfaceContainerHighest = dolphinColorNeutral4White,
)

private val darkMaterialColorScheme = darkColorScheme(
    primary = dolphinColorPrimary1Black,
    onPrimary = dolphinColorTextOnimage1Black,
    primaryContainer = dolphinColorPrimary7Black,
    onPrimaryContainer = dolphinColorPrimary1Black,
    secondary = dolphinColorSecondary2_1Black,
    onSecondary = dolphinColorTextOnimage1Black,
    secondaryContainer = dolphinColorSecondary2_4Black,
    onSecondaryContainer = dolphinColorSecondary2_1Black,
    tertiary = dolphinColorSecondary7Black,
    onTertiary = dolphinColorTextOnimage1Black,
    tertiaryContainer = dolphinColorSecondary7_2Black,
    onTertiaryContainer = dolphinColorSecondary7Black,
    error = dolphinColorSecondary4Black,
    onError = dolphinColorTextOnimage1Black,
    errorContainer = dolphinColorPrimary7Black,
    onErrorContainer = dolphinColorPrimary1Black,
    background = dolphinColorBackgroundAndroidBlack,
    onBackground = dolphinColorText1Black,
    surface = dolphinColorBackgroundDualBlack,
    onSurface = dolphinColorText1Black,
    onSurfaceVariant = dolphinColorText3_1Black,
    outline = dolphinColorText6_1Black,
    outlineVariant = dolphinColorText7Black,
    scrim = dolphinColorText4_1Black,
    surfaceVariant = dolphinColorSkinElement1Black,
    inverseSurface = dolphinColorBackgroundWhiteWhite,
    inverseOnSurface = dolphinColorText1White,
    inversePrimary = dolphinColorPrimary1White,
    surfaceDim = dolphinColorBackgroundAndroidBlack,
    surfaceBright = dolphinColorNeutral6Black,
    surfaceContainerLowest = dolphinColorBackgroundAndroidBlack,
    surfaceContainerLow = dolphinColorBackgroundDualBlack,
    surfaceContainer = dolphinColorSkinElement2Black,
    surfaceContainerHigh = dolphinColorSkinElement5Black,
    surfaceContainerHighest = dolphinColorNeutral7_1Black,
)

private val whiteDolphinColors = DolphinColors(
    avatarBg1 = dolphinColorAvatarBg1White,
    avatarBg2 = dolphinColorAvatarBg2White,
    avatarBg3 = dolphinColorAvatarBg3White,
    avatarBg4 = dolphinColorAvatarBg4White,
    avatarBg5 = dolphinColorAvatarBg5White,
    avatarBg6 = dolphinColorAvatarBg6White,
    backgroundAndroid = dolphinColorBackgroundAndroidWhite,
    backgroundDual = dolphinColorBackgroundDualWhite,
    backgroundIOS = dolphinColorBackgroundIOSWhite,
    backgroundWhite = dolphinColorBackgroundWhiteWhite,
    brand1 = dolphinColorBrand1White,
    brand2 = dolphinColorBrand2White,
    brand3 = dolphinColorBrand3White,
    brand4 = dolphinColorBrand4White,
    brand5 = dolphinColorBrand5White,
    brand6 = dolphinColorBrand6White,
    brand7 = dolphinColorBrand7White,
    brand8 = dolphinColorBrand8White,
    brand9 = dolphinColorBrand9White,
    brand10 = dolphinColorBrand10White,
    icon1 = dolphinColorIcon1White,
    icon2 = dolphinColorIcon2White,
    icon3 = dolphinColorIcon3White,
    icon4 = dolphinColorIcon4White,
    icon5 = dolphinColorIcon5White,
    icon6 = dolphinColorIcon6White,
    icon7 = dolphinColorIcon7White,
    iconDual1 = dolphinColorIconDual1White,
    iconDual1_1 = dolphinColorIconDual1_1White,
    iconDual2 = dolphinColorIconDual2White,
    iconDual2_1 = dolphinColorIconDual2_1White,
    iconDual3 = dolphinColorIconDual3White,
    iconDual4 = dolphinColorIconDual4White,
    iconDual5 = dolphinColorIconDual5White,
    iconDual6 = dolphinColorIconDual6White,
    iconDual7 = dolphinColorIconDual7White,
    iconDual7_1 = dolphinColorIconDual7_1White,
    iconDual7_2 = dolphinColorIconDual7_2White,
    iconDual8 = dolphinColorIconDual8White,
    iconDual9 = dolphinColorIconDual9White,
    iconOnimage1 = dolphinColorIconOnimage1White,
    iconOnimage2 = dolphinColorIconOnimage2White,
    iconOnimage3 = dolphinColorIconOnimage3White,
    iconOnimage4 = dolphinColorIconOnimage4White,
    iconOnimage5 = dolphinColorIconOnimage5White,
    iconOnimage6 = dolphinColorIconOnimage6White,
    iconOnimage7 = dolphinColorIconOnimage7White,
    neutral3 = dolphinColorNeutral3White,
    neutral4 = dolphinColorNeutral4White,
    neutral5 = dolphinColorNeutral5White,
    neutral6 = dolphinColorNeutral6White,
    neutral6_1 = dolphinColorNeutral6_1White,
    neutral7 = dolphinColorNeutral7White,
    neutral7_1 = dolphinColorNeutral7_1White,
    neutral8 = dolphinColorNeutral8White,
    neutral8_1 = dolphinColorNeutral8_1White,
    neutral9 = dolphinColorNeutral9White,
    neutral10 = dolphinColorNeutral10White,
    neutral11 = dolphinColorNeutral11White,
    primary1 = dolphinColorPrimary1White,
    primary2 = dolphinColorPrimary2White,
    primary3 = dolphinColorPrimary3White,
    primary4 = dolphinColorPrimary4White,
    primary5 = dolphinColorPrimary5White,
    primary6 = dolphinColorPrimary6White,
    primary7 = dolphinColorPrimary7White,
    secondary1_1 = dolphinColorSecondary1_1White,
    secondary1_2 = dolphinColorSecondary1_2White,
    secondary1_3 = dolphinColorSecondary1_3White,
    secondary2_1 = dolphinColorSecondary2_1White,
    secondary2_2 = dolphinColorSecondary2_2White,
    secondary2_3 = dolphinColorSecondary2_3White,
    secondary2_4 = dolphinColorSecondary2_4White,
    secondary3 = dolphinColorSecondary3White,
    secondary4 = dolphinColorSecondary4White,
    secondary5 = dolphinColorSecondary5White,
    secondary6 = dolphinColorSecondary6White,
    secondary7 = dolphinColorSecondary7White,
    secondary7_2 = dolphinColorSecondary7_2White,
    secondary8 = dolphinColorSecondary8White,
    secondary9 = dolphinColorSecondary9White,
    skinElement1 = dolphinColorSkinElement1White,
    skinElement2 = dolphinColorSkinElement2White,
    skinElement3 = dolphinColorSkinElement3White,
    skinElement4 = dolphinColorSkinElement4White,
    skinElement5 = dolphinColorSkinElement5White,
    skinElement6 = dolphinColorSkinElement6White,
    skinElement7 = dolphinColorSkinElement7White,
    skinElement10 = dolphinColorSkinElement10White,
    text1 = dolphinColorText1White,
    text2 = dolphinColorText2White,
    text2_1 = dolphinColorText2_1White,
    text3 = dolphinColorText3White,
    text3_1 = dolphinColorText3_1White,
    text4 = dolphinColorText4White,
    text4_1 = dolphinColorText4_1White,
    text5 = dolphinColorText5White,
    text5_1 = dolphinColorText5_1White,
    text6 = dolphinColorText6White,
    text6_1 = dolphinColorText6_1White,
    text7 = dolphinColorText7White,
    textDual1 = dolphinColorTextDual1White,
    textDual2 = dolphinColorTextDual2White,
    textDual3 = dolphinColorTextDual3White,
    textDual4 = dolphinColorTextDual4White,
    textDual5 = dolphinColorTextDual5White,
    textDual6 = dolphinColorTextDual6White,
    textOnimage1 = dolphinColorTextOnimage1White,
    textOnimage1_1 = dolphinColorTextOnimage1_1White,
    textOnimage2 = dolphinColorTextOnimage2White,
    textOnimage3 = dolphinColorTextOnimage3White,
    textOnimage3_1 = dolphinColorTextOnimage3_1White,
    textOnimage4 = dolphinColorTextOnimage4White,
    textOnimage5 = dolphinColorTextOnimage5White,
    textOnimage6 = dolphinColorTextOnimage6White,
    textOnimage7 = dolphinColorTextOnimage7White,
    textOnimage8 = dolphinColorTextOnimage8White,
    textOnimage9 = dolphinColorTextOnimage9White,
    textOnimage10 = dolphinColorTextOnimage10White,
)

val blackDolphinColors = DolphinColors(
    avatarBg1 = dolphinColorAvatarBg1Black,
    avatarBg2 = dolphinColorAvatarBg2Black,
    avatarBg3 = dolphinColorAvatarBg3Black,
    avatarBg4 = dolphinColorAvatarBg4Black,
    avatarBg5 = dolphinColorAvatarBg5Black,
    avatarBg6 = dolphinColorAvatarBg6Black,
    backgroundAndroid = dolphinColorBackgroundAndroidBlack,
    backgroundDual = dolphinColorBackgroundDualBlack,
    backgroundIOS = dolphinColorBackgroundIOSBlack,
    backgroundWhite = dolphinColorBackgroundWhiteBlack,
    brand1 = dolphinColorBrand1Black,
    brand2 = dolphinColorBrand2Black,
    brand3 = dolphinColorBrand3Black,
    brand4 = dolphinColorBrand4Black,
    brand5 = dolphinColorBrand5Black,
    brand6 = dolphinColorBrand6Black,
    brand7 = dolphinColorBrand7Black,
    brand8 = dolphinColorBrand8Black,
    brand9 = dolphinColorBrand9Black,
    brand10 = dolphinColorBrand10Black,
    icon1 = dolphinColorIcon1Black,
    icon2 = dolphinColorIcon2Black,
    icon3 = dolphinColorIcon3Black,
    icon4 = dolphinColorIcon4Black,
    icon5 = dolphinColorIcon5Black,
    icon6 = dolphinColorIcon6Black,
    icon7 = dolphinColorIcon7Black,
    iconDual1 = dolphinColorIconDual1Black,
    iconDual1_1 = dolphinColorIconDual1_1Black,
    iconDual2 = dolphinColorIconDual2Black,
    iconDual2_1 = dolphinColorIconDual2_1Black,
    iconDual3 = dolphinColorIconDual3Black,
    iconDual4 = dolphinColorIconDual4Black,
    iconDual5 = dolphinColorIconDual5Black,
    iconDual6 = dolphinColorIconDual6Black,
    iconDual7 = dolphinColorIconDual7Black,
    iconDual7_1 = dolphinColorIconDual7_1Black,
    iconDual7_2 = dolphinColorIconDual7_2Black,
    iconDual8 = dolphinColorIconDual8Black,
    iconDual9 = dolphinColorIconDual9Black,
    iconOnimage1 = dolphinColorIconOnimage1Black,
    iconOnimage2 = dolphinColorIconOnimage2Black,
    iconOnimage3 = dolphinColorIconOnimage3Black,
    iconOnimage4 = dolphinColorIconOnimage4Black,
    iconOnimage5 = dolphinColorIconOnimage5Black,
    iconOnimage6 = dolphinColorIconOnimage6Black,
    iconOnimage7 = dolphinColorIconOnimage7Black,
    neutral3 = dolphinColorNeutral3Black,
    neutral4 = dolphinColorNeutral4Black,
    neutral5 = dolphinColorNeutral5Black,
    neutral6 = dolphinColorNeutral6Black,
    neutral6_1 = dolphinColorNeutral6_1Black,
    neutral7 = dolphinColorNeutral7Black,
    neutral7_1 = dolphinColorNeutral7_1Black,
    neutral8 = dolphinColorNeutral8Black,
    neutral8_1 = dolphinColorNeutral8_1Black,
    neutral9 = dolphinColorNeutral9Black,
    neutral10 = dolphinColorNeutral10Black,
    neutral11 = dolphinColorNeutral11Black,
    primary1 = dolphinColorPrimary1Black,
    primary2 = dolphinColorPrimary2Black,
    primary3 = dolphinColorPrimary3Black,
    primary4 = dolphinColorPrimary4Black,
    primary5 = dolphinColorPrimary5Black,
    primary6 = dolphinColorPrimary6Black,
    primary7 = dolphinColorPrimary7Black,
    secondary1_1 = dolphinColorSecondary1_1Black,
    secondary1_2 = dolphinColorSecondary1_2Black,
    secondary1_3 = dolphinColorSecondary1_3Black,
    secondary2_1 = dolphinColorSecondary2_1Black,
    secondary2_2 = dolphinColorSecondary2_2Black,
    secondary2_3 = dolphinColorSecondary2_3Black,
    secondary2_4 = dolphinColorSecondary2_4Black,
    secondary3 = dolphinColorSecondary3Black,
    secondary4 = dolphinColorSecondary4Black,
    secondary5 = dolphinColorSecondary5Black,
    secondary6 = dolphinColorSecondary6Black,
    secondary7 = dolphinColorSecondary7Black,
    secondary7_2 = dolphinColorSecondary7_2Black,
    secondary8 = dolphinColorSecondary8Black,
    secondary9 = dolphinColorSecondary9Black,
    skinElement1 = dolphinColorSkinElement1Black,
    skinElement2 = dolphinColorSkinElement2Black,
    skinElement3 = dolphinColorSkinElement3Black,
    skinElement4 = dolphinColorSkinElement4Black,
    skinElement5 = dolphinColorSkinElement5Black,
    skinElement6 = dolphinColorSkinElement6Black,
    skinElement7 = dolphinColorSkinElement7Black,
    skinElement10 = dolphinColorSkinElement10Black,
    text1 = dolphinColorText1Black,
    text2 = dolphinColorText2Black,
    text2_1 = dolphinColorText2_1Black,
    text3 = dolphinColorText3Black,
    text3_1 = dolphinColorText3_1Black,
    text4 = dolphinColorText4Black,
    text4_1 = dolphinColorText4_1Black,
    text5 = dolphinColorText5Black,
    text5_1 = dolphinColorText5_1Black,
    text6 = dolphinColorText6Black,
    text6_1 = dolphinColorText6_1Black,
    text7 = dolphinColorText7Black,
    textDual1 = dolphinColorTextDual1Black,
    textDual2 = dolphinColorTextDual2Black,
    textDual3 = dolphinColorTextDual3Black,
    textDual4 = dolphinColorTextDual4Black,
    textDual5 = dolphinColorTextDual5Black,
    textDual6 = dolphinColorTextDual6Black,
    textOnimage1 = dolphinColorTextOnimage1Black,
    textOnimage1_1 = dolphinColorTextOnimage1_1Black,
    textOnimage2 = dolphinColorTextOnimage2Black,
    textOnimage3 = dolphinColorTextOnimage3Black,
    textOnimage3_1 = dolphinColorTextOnimage3_1Black,
    textOnimage4 = dolphinColorTextOnimage4Black,
    textOnimage5 = dolphinColorTextOnimage5Black,
    textOnimage6 = dolphinColorTextOnimage6Black,
    textOnimage7 = dolphinColorTextOnimage7Black,
    textOnimage8 = dolphinColorTextOnimage8Black,
    textOnimage9 = dolphinColorTextOnimage9Black,
    textOnimage10 = dolphinColorTextOnimage10Black,
)

val whiteDolphinShadows = DolphinShadows(
    bubble = dolphinShadowBubbleWhite,
    dark = dolphinShadowDarkWhite,
    gray = dolphinShadowGrayWhite,
    normal = dolphinShadowNormalWhite,
    redBtn = dolphinShadowRedBtnWhite,
    redIcon = dolphinShadowRedIconWhite,
    toast = dolphinShadowToastWhite
)

val blackDolphinShadows = DolphinShadows(
    bubble = dolphinShadowBubbleBlack,
    dark = dolphinShadowDarkBlack,
    gray = dolphinShadowGrayBlack,
    normal = dolphinShadowNormalBlack,
    redBtn = dolphinShadowRedBtnBlack,
    redIcon = dolphinShadowRedIconBlack,
    toast = dolphinShadowToastBlack
)

val LocalDolphinColors = staticCompositionLocalOf {
    DolphinColors()
}

val LocalDolphinShadows = staticCompositionLocalOf { DolphinShadows() }

@Composable
fun DolphinTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
) {
    val materialColors = if (darkTheme) darkMaterialColorScheme else lightMaterialColorScheme
    val dolphinColors = if (darkTheme) blackDolphinColors else whiteDolphinColors

    val dolphinShadows = if (darkTheme) blackDolphinShadows else whiteDolphinShadows

    CompositionLocalProvider(
        LocalDolphinColors provides dolphinColors,
        LocalDolphinShadows provides dolphinShadows
    ) {
        MaterialTheme(
            colorScheme = materialColors,
            content = content
        )
    }
}

object DolphinTheme {
    val colors: DolphinColors
        @Composable
        @ReadOnlyComposable
        get() = LocalDolphinColors.current

    val shadows: DolphinShadows
        @Composable
        @ReadOnlyComposable
        get() = LocalDolphinShadows.current
}